### PR TITLE
Add  Accounts and Locations API

### PR DESCRIPTION
**Pull request by bfcamara**
This PR adds the Accounts and Locations API

### CODE REVIEW

**Comment by bryanmacfarlane** [comment]
Can you update markdown docs and get this in?  Might need to bump version to 3.2 now

**Comment by bfcamara** [comment]
Most of this code was generated a few months ago. I would suggest to regenerate it again. I am not working in VSTS anymore so I'm not able to regenerate it.

**Comment by murmanda** [comment]
Please merge this PR as the conflicts seem to be uncritical for me. I need to be able to check the current account and memberships of other accounts etc

**Comment by ferdiozturk** [comment]
Please merge this PR as the conflicts seem to be uncritical for me. I need to be able to check the current account and memberships of other accounts etc

**Comment by bryanmacfarlane** [comment]
we'll need to regenerate

**Comment by bryanmacfarlane** [comment]
not needed.  we regenerated and got these now

**Pull request closed without merging**
