### PR TITLE
Adding Wiki NodeJs APIs

### PR DESCRIPTION
**Pull request by GiridharanNarayanan**
Adding Wiki REST APIs

### CODE REVIEW

**Comment by stephenmichaelf** [comment]
@GiridharanNarayanan could you add a sample usage of the Wiki api [here](https://github.com/Microsoft/vsts-node-api/blob/master/samples/creation.ts)? It shows others how to use it and also serves as an acceptance test to make sure the service is working, at least at a high level. Thanks!

**Comment by GiridharanNarayanan** [comment]
@stephenmichaelf , I have added the acceptance test for wiki.

**Comment by stephenmichaelf** [comment]
Thanks! Were you able to run all of the creation samples, including this new one, and saw they were successful? I will pull and test too. Otherwise LGTM.

Also please bump minor version in package.json.

**Comment by GiridharanNarayanan** [comment]
@stephenmichaelf , I have tried the samples including the new one and have updated the package.json.

PS: I hit into some error during running samples from samples of other areas, so I tried running samples with Wiki as the first one in the samples. That worked. Post trying out the samples, moved the Wiki samples to its alphabetical position.

**Comment by stephenmichaelf** [comment]
Thanks for making the updates! I should have a few minutes to quickly test this today then we can probably merge.

Are you done with changes on your end?

**Comment by stephenmichaelf** [comment]
Taking a look today, sorry about that! Lots going on this week.

**Comment by GiridharanNarayanan** [comment]
Thanks @stephenmichaelf .

**Pull request merged**
