### PR TITLE
Add HTTPS request proxy support

### PR DESCRIPTION
**Pull request by gregjhogan**
Fix for #35

### CODE REVIEW

**Comment by bryanmacfarlane** [comment]
I'm very interested in this PR.  Sorry for the delay.  Are you interested in resolving conflicts and getting this in?

**Comment by gregjhogan** [comment]
@bryanmacfarlane conflicts resolved ... looks like you removed `<reference path="..."/>` so not sure how you want to handle the tunnel module typescript definition (which I had to author)

**Comment by bryanmacfarlane** [comment]
@gregjhogan - we're you able to test with a actual proxy?

**Comment by bryanmacfarlane** [comment]
I tested.  Couple tweaks to add but I'll merge and fix

**Pull request merged**
