### PR TITLE
Stop using gulp-tsc, start using gulp-typescript

### PR DESCRIPTION
**Pull request by ryanmolden**
See issue #16

### CODE REVIEW

**Comment by bryanmacfarlane** [comment]
I used to use gulp-typescript and had issues every time new and preview drops of typescript came out.  Turns out calling tsc (that I install) just works.

**Comment by ryanmolden** [comment]
That confuses me. gulp-tsc uses where to find tsc.exe, which means it ends up (on a Windows box with VS installed) calling the TSC that VS installs, which is 1.0. If I upgrade VS your build using gulp-tsc suddenly starts using a new compiler, so gulp-tsc does not isolate you from new/preview versions, quite the opposite.

gulp-typescript on the other hand uses the MS published TS compiler from npm, so if you have a set dependency on gulp-typescript version X then you ALWAYS will have a typescript compiler on the box that matches version X of gulp-typescript and it won't matter if I upgrade or even uninstall VS, your code will continue to build and be locked to a specific TS compiler version.

Is it because you were saying >=<some version> for your gulp-tsc dependency? I could see auto TS updates in that situation, but your no more isolated than if VS Update X decides to push out a new TS compiler, unless you don't install VS on your box, or the TS tools apart from whatever one you happen to know works with the project.

**Comment by bryanmacfarlane** [comment]
that sounds like an issue with VS.  It's simple tsc just calls the typescript on your box which is what I'm after (allows me to pick up newer ts versions).

**Comment by bryanmacfarlane** [comment]
we ended up switching to gulp-typescript later.  thx

**Pull request closed without merging**
